name: rollbar_common
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^1.11.0
  mockito: '>=5.0.0 <6.0.0'
  pubspec_parse: '>=0.1.8 <=1.0.0'
dependencies: 
  meta: ^1.7.0
