name: rollbar_common
description: Commons package used by the Rollbar Dart and Flutter SDKs for error reporting.
version: 0.3.0-beta
homepage: https://www.rollbar.com
documentation: https://docs.rollbar.com/docs/flutter#flutter
repository: https://github.com/rollbar/rollbar-flutter

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  meta: ^1.7.0
  logging: ^1.0.2

dev_dependencies:
  lints: '>=1.0.0 <3.0.0'
  test: ^1.16.0
  build_runner: ^2.1.8
  mockito: ^5.1.0
  pubspec_parse: ^1.2.0
