name: rollbar_dart_example
description: Demonstrates how to use rollbar-dart

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  logging: ^1.0.2
  rollbar_dart: ^0.3.0-beta

dependency_overrides:
  rollbar_common:
    path: ../../rollbar_common
  rollbar_dart:
    path: ..

dev_dependencies:
  pedantic: '>=1.9.2 <1.12.0'
