# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.

include: package:flutter_lints/flutter.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

linter:
  rules:
    - always_declare_return_types
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - unsafe_html
    - use_full_hex_values_for_flutter_colors
    # - cancel_subscriptions
    # - close_sinks
    # - comment_references
    # - one_member_abstracts
    # - only_throw_errors
    # - package_api_docs
    # - prefer_final_in_for_each

analyzer:
  exclude:
    - 'example/**'
