name: rollbar_flutter
description: Connect your Flutter applications to Rollbar for error reporting.
version: 0.3.0-beta
homepage: https://www.rollbar.com
documentation: https://docs.rollbar.com/docs/flutter#flutter
repository: https://github.com/rollbar/rollbar-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  connectivity_plus: ^2.1.0
  flutter:
    sdk: flutter
  logging: ^1.0.2
  meta: ^1.7.0
  rollbar_common: '>=0.2.0-beta <1.0.0'
  rollbar_dart: '>=0.2.0-beta <1.0.0'

dependency_overrides:
  rollbar_common:
    path: ../rollbar_common
  rollbar_dart:
    path: ../rollbar_dart
 
dev_dependencies:
  lints: ^1.0.1
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  build_runner: ^1.11.0
  mockito: '>=5.0.0 <6.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.rollbar.flutter
        pluginClass: RollbarFlutterPlugin
      ios:
        pluginClass: RollbarFlutterPlugin
