name: rollbar_flutter
description: Connect your Flutter applications to Rollbar for error reporting.
version: 0.3.0-beta
homepage: https://www.rollbar.com
documentation: https://docs.rollbar.com/docs/flutter#flutter
repository: https://github.com/rollbar/rollbar-flutter

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=2.8.1'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  connectivity_plus: ^2.3.6
  sqlite3_flutter_libs: ^0.5.8
  rollbar_common: ^0.3.1-beta
  rollbar_dart: ^0.3.0-beta

dependency_overrides:
  rollbar_common:
    path: ../rollbar_common
  rollbar_dart:
    path: ../rollbar_dart

dev_dependencies:
  lints: '>=1.0.0 <3.0.0'
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  connectivity_plus_platform_interface: ^1.2.1
  plugin_platform_interface: ^2.1.2
  build_runner: ^2.2.0
  mockito: ^5.2.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rollbar.flutter
        pluginClass: RollbarFlutterPlugin
      ios:
        pluginClass: RollbarFlutterPlugin
