name: rollbar_dart
description: Connect your Dart applications to Rollbar for error reporting.
version: 0.3.0-beta
homepage: https://www.rollbar.com
documentation: https://docs.rollbar.com/docs/flutter#dart
repository: https://github.com/rollbar/rollbar-flutter

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  http: ^0.13.4
  meta: ^1.7.0
  stack_trace: ^1.10.0
  logging: ^1.0.2
  rollbar_common: ^0.3.1-beta

dependency_overrides:
  rollbar_common:
    path: ../rollbar_common

dev_dependencies:
  lints: '>=1.0.0 <3.0.0'
  test: ^1.16.0
  build_runner: ^2.1.8
  mockito: ^5.0.0
  pubspec_parse: ^1.2.0
