name: rollbar_dart
description: Connect your Dart applications to Rollbar for error reporting
version: 0.2.0-beta
homepage: https://www.rollbar.com
documentation: https://docs.rollbar.com/docs/flutter#dart
repository: https://github.com/rollbar/rollbar-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  http: '>=0.12.2 <0.14.0'
  stack_trace: '>=1.9.5 <1.11.0'

dev_dependencies:
  # pedantic: '>=1.9.2 <1.12.0'
  lints: ^1.0.1
  test: ^1.14.4
  build_runner: ^1.11.0
  mockito: '>=5.0.0 <6.0.0'
  pubspec_parse: '>=0.1.8 <=1.0.0'
